#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ffc-ahwr$ --format={{.Name}})" ]; then
  echo "Creating ffc-ahwr Docker network"
  docker network create ffc-ahwr
fi

# Determine which docker compose command is available
if command -v docker compose &> /dev/null; then
  compose_cmd="docker compose"
elif command -v docker-compose &> /dev/null; then
  compose_cmd="docker-compose"
else
  echo "Neither 'docker compose' nor 'docker-compose' is installed." >&2
  exit 1
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

# Ensure the shared external network exists
network_name="ahwr-local"
if ! docker network inspect "$network_name" >/dev/null 2>&1; then
  echo "Creating external network: $network_name"
  docker network create "$network_name"
fi

$compose_cmd down

$compose_cmd \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  up "$@"